defmodule Taskman.Repo.Migrations.AddAccountsAuthentication do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :api_key_hash, :binary, null: false
      add :expires_at, :utc_datetime_usec, null: false
      add :revoked_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create unique_index(:api_keys, [:api_key_hash], name: "api_keys_unique_api_key_hash_index")

    create table(:tokens, primary_key: false) do
      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :extra_data, :map
      add :purpose, :text, null: false
      add :expires_at, :utc_datetime, null: false
      add :subject, :text, null: false
      add :jti, :text, null: false, primary_key: true
    end

    create table(:users, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:api_keys) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "api_keys_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:users) do
      add :email, :citext, null: false
      add :hashed_password, :text
      add :status, :text, null: false, default: "pending"
      add :admin?, :boolean, null: false, default: false
      add :confirmed_at, :utc_datetime_usec

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:users, [:email], name: "users_unique_email_index")
  end

  def down do
    drop_if_exists unique_index(:users, [:email], name: "users_unique_email_index")

    alter table(:users) do
      remove :updated_at
      remove :inserted_at
      remove :confirmed_at
      remove :admin?
      remove :status
      remove :hashed_password
      remove :email
    end

    drop constraint(:api_keys, "api_keys_user_id_fkey")

    alter table(:api_keys) do
      modify :user_id, :uuid
    end

    drop table(:users)

    drop table(:tokens)

    drop_if_exists unique_index(:api_keys, [:api_key_hash],
                     name: "api_keys_unique_api_key_hash_index"
                   )

    drop table(:api_keys)
  end
end
